name: media-catcher
base: core22
version: '1.0.1'
summary: Modern GUI application for downloading videos and audio from online platforms
description: |
  Media Catcher is a modern GUI application for downloading videos and audio from
  YouTube and other platforms. Built with Python and CustomTkinter for a sleek,
  user-friendly interface.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  media-catcher:
    command: bin/media-catcher-launch
    desktop: usr/share/applications/media-catcher.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  media-catcher:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - python3-tk
      - python3-pil
      - python3-pil.imagetk
      - libtkinter-img
      - python3-requests
      - python3-urllib3
      - ffmpeg
    organize:
      media_catcher.py: bin/media_catcher.py
      themes.json: bin/themes.json
      media-catcher.png: usr/share/pixmaps/media-catcher.png
      media-catcher-launch: bin/media-catcher-launch
    override-build: |
      craftctl default
      
      # Vytvor launch script
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/media-catcher-launch << 'EOF'
#!/usr/bin/env python3
import sys
import os

# Pridaj snap python path
snap_dir = os.environ.get('SNAP', '/snap/media-catcher/current')
sys.path.insert(0, os.path.join(snap_dir, 'bin'))
sys.path.insert(0, os.path.join(snap_dir, 'lib/python3.10/site-packages'))

# Spusti aplikáciu
try:
    import media_catcher
    media_catcher.main()
except Exception as e:
    print(f"Error starting Media Catcher: {e}")
    import traceback
    traceback.print_exc()
EOF
      chmod +x $CRAFT_PART_INSTALL/bin/media-catcher-launch
      
      # Vytvor desktop file
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cat > $CRAFT_PART_INSTALL/usr/share/applications/media-catcher.desktop << 'EOF'
[Desktop Entry]
Type=Application
Name=Media Catcher
Comment=Download videos and audio from online platforms
Exec=media-catcher
Icon=${SNAP}/usr/share/pixmaps/media-catcher.png
Categories=AudioVideo;Audio;Video;Network;
Keywords=download;video;audio;youtube;media;
StartupNotify=true
EOF
